version: "3.8"
services:
  frontend:
    image: ghcr.io/clicepfl/clicketing:main
    environment:
      DIRECTUS_URL: https://clic.epfl.ch/directus
      DIRECTUS_TOKEN: ${DIRECTUS_TOKEN}
    ports:
      - 8007:3000
