version: "3.8"
services:
  synapse:
    image: matrixdotorg/synapse:v1.126.0
    volumes:
      - data:/data
      - ${CONFIG_PATH}:/data/homeserver.yaml
    depends_on:
      - generate
      - database
    ports:
      - 8011:8008

  database:
    image: postgres:15.4-alpine3.18
    volumes:
      - database:/var/lib/postgresql/data
      - ${DATABASE_INIT}:/docker-entrypoint-initdb.d
    environment:
      TZ: UTC
      POSTGRES_USER: synapse
      POSTGRES_DB: synapse
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C" # Because python
    ports:
      - 5007:5432

volumes:
  data:
  database:
