- name: Create KeyCLIC theme folder
  ansible.builtin.file:
    path: "{{ role_path }}/files/clic_theme"
    mode: "0755"
    state: directory

- name: Download the KeyCLIC theme
  ansible.builtin.get_url:
    url: https://github.com/clicepfl/keyclic-theme/releases/download/v0.1.0/keycloak-theme-for-kc-all-other-versions.jar
    dest: "{{ role_path }}/files/clic_theme/clic-theme.jar"
    mode: "0644"

- name: Using default deploy method
  community.docker.docker_stack:
    state: present
    name: keycloak
    resolve_image: always
    compose:
      - "{{ role_path }}/files/docker-compose.yaml"
  environment:
    ADMIN_PASSWORD: "{{ service.admin_password }}"
    DB_PASSWORD: "{{ service.database.password }}"
    DB_INIT: "{{ service.database.init }}"
    BASE_PATH: "{{ role_path }}"
