- name: Get config
  ansible.builtin.git:
    repo: https://github.com/clicepfl/directus-config
    dest: "{{ role_path }}/files/directus-config"

- name: Using default deploy method
  community.docker.docker_stack:
    state: present
    name: directus
    resolve_image: always
    compose:
      - "{{ role_path }}/files/docker-compose.yaml"
  environment:
    MAIL_SENDER_SECRET: "{{ service.mail_sender_secret }}"
    ADMIN_PASSWORD: "{{ service.admin_password }}"
    KEYCLOAK_SECRET: "{{ service.keycloak_secret }}"
    SECRET: "{{ service.secret }}"
    KEY: "{{ service.key }}"
    DATABASE_INIT: "{{ service.database.init }}"
    DATABASE_PASSWORD: "{{ service.database.password }}"
    SMTP_IT_PASSWORD: "{{ general.mail.it_password }}"
    BASE_PATH: "{{ role_path }}"
    CONFIG_PATH: "{{ role_path }}/files/directus-config"
