- name: Get config
  ansible.builtin.git:
    repo: https://github.com/clicepfl/directus-config
    dest: "{{ role_path }}/files/directus-config"

- name: Using default deploy method
  community.docker.docker_stack:
    state: present
    name: directus
    resolve_image: always
    compose:
      - "{{ role_path }}/files/docker-compose.yaml"
  environment:
    MAIL_SENDER_SECRET: "{{ service.mail_sender_secret }}"
    ADMIN_PASSWORD: "{{ service.admin_password }}"
    KEYCLOAK_SECRET: "{{ service.keycloak_secret }}"
    SECRET: "{{ service.secret }}"
    KEY: "{{ service.key }}"
    DATABASE_INIT: "{{ service.database.init }}"
    DATABASE_PASSWORD: "{{ service.database.password }}"
    SMTP_IT_PASSWORD: "{{ general.mail.it_password }}"
    BASE_PATH: "{{ role_path }}"

- name: Wait for directus to be available
  ansible.builtin.wait_for:
    port: 8001

- name: Get directus container id
  ansible.builtin.command:
    cmd: docker service ps directus_directus --filter desired-state=running -q
  changed_when: false
  register: ps

- name: Compute directus container name
  ansible.builtin.set_fact:
    directus_container_name: directus_directus.1.{{ ps.stdout }}

- name: Get database container id
  ansible.builtin.command:
    cmd: docker service ps directus_database --filter desired-state=running -q
  changed_when: false
  register: ps

- name: Compute database container name
  ansible.builtin.set_fact:
    database_container_name: directus_database.1.{{ ps.stdout }}

- name: Copy schema into container
  community.docker.docker_container_copy_into:
    container: "{{ directus_container_name }}"
    container_path: /snapshot.yaml
    path: "{{ role_path }}/files/directus-config/snapshot.yaml"

- name: Apply schema
  community.docker.docker_container_exec:
    container: "{{ directus_container_name }}"
    command: npx directus schema apply /snapshot.yaml -y

- name: Copy schema into container
  community.docker.docker_container_copy_into:
    container: "{{ database_container_name }}"
    container_path: /flows.sql
    path: "{{ role_path }}/files/directus-config/flows.sql"

- name: Apply flows dump
  community.docker.docker_container_exec:
    container: "{{ database_container_name }}"
    command: psql -U directus_user directus_data -f /flows.sql

- name: Restart directus container
  community.docker.docker_container:
    name: "{{ directus_container_name }}"
    state: stopped # The swarm will take care of booting up a new container
