argument_specs:
  main:
    options:
      service:
        type: "dict"
        required: true
        options:
          secret:
            required: true

      general:
        type: "dict"
        required: true
        options:
          mail:
            type: "dict"
            required: true
            options:
              it_password:
                required: true
              comm_password:
                required: true
          config_dir:
            required: true