version: "3.8"
services:
  website:
    image: ghcr.io/clicgamestar/website:main
    hostname: gamestar-website
    environment:
      DIRECTUS_TOKEN: ${DIRECTUS_TOKEN}
    ports:
      - 8016:3000
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
