version: "3.8"
services:
  vaultwarden:
    image: vaultwarden/server:1.33.2-alpine
    hostname: vaultwarden
    volumes:
      - vaultwarden:/data
    environment:
      DOMAIN: http://localhost/armoire
      ADMIN_TOKEN: ${ADMIN_TOKEN}
    ports:
      - 8003:80
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M

volumes:
  vaultwarden: